  
- name: Update-XML
  hosts: localhost
  connection: local
  
#Environment variables defined
  environment:
    F5_USER: "{{ F5_Username }}"
    F5_PASSWORD: "{{ F5_Password }}"
    F5_SERVER_PORT: "{{ F5_Admin_Port }}" #"443"
    F5_VALIDATE_CERTS: "False"
    F5_SERVER: "{{ F5_IPAddress }}"
  
  tasks:

#create Disallowed URLs Section if missing
  - name: Add Disallowed URLs
    xml:
      path: "{{ ASM_Policy }}" 
      input_type: xml
      pretty_print: yes
      insertafter: yes  
      xpath: /policy/urls/url[*]
      add_children: "<disallowed_urls></disallowed_urls>"
    when: "'<disallowed_urls>' not in lookup('file', ASM_Policy  )"
  
#Import Additional Disallowed URLs 
  - name: Add Disallowed URLs
    xml:
      path: "{{ ASM_Policy }}" 
      input_type: xml
      pretty_print: yes
      xpath: /policy/urls/disallowed_urls
      add_children: 
        - "<url protocol=\"HTTP\" type=\"explicit\" name=\"{{ item }}\"/>"
        - "<url protocol=\"HTTPS\" type=\"explicit\" name=\"{{ item }}\"/>"
    with_items: "{{ Blocked_URLs }}"
  
#Re-Deploy ASM policy
  - name: Create an LTM policy
    bigip_policy:
     name: asm-policy
     state: present

  - name: Import ASM policy
    bigip_asm_policy_import:
     name: Demo
     source: "{{ ASM_Policy }}" 
     force: yes

  - name: Activate ASM policy
    bigip_asm_policy_manage:
     name: Demo
     active: yes
     state: present

  - name: Replace a forward action with an ASM action
    bigip_policy_rule:
     policy: asm-policy
     name: rule1
     actions:
     - type: enable
       asm_policy: Demo
       
 #Re-Deploy Draft ASM policy
  - name: Deploy Draft ASM policy
    bigip_policy:
     name: asm-policy
     state: present
